import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Smooth Scroll | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <ul>
            <li><Link href="/">Services</Link></li>
            <li><Link href="/stories">Stories</Link></li>
            <li><Link href="/podcast">Podcast</Link></li>
            <li><Link href="/about">About</Link></li>
          </ul>
        </nav>
      </header>
      <main className={styles.main}>
      </main>

      <footer className={styles.footer}>
        <nav>
          <ul>
            <li><Link href="/">Services</Link></li>
            <li><Link href="/stories">Stories</Link></li>
            <li><Link href="/podcast">Podcast</Link></li>
            <li><Link href="/about">About</Link></li>
          </ul>
        </nav>
      </footer>
    </div>
  )
}
